kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: kag-2
  labels:
    app: kag-2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kag-2
    spec:
      containers:
      - name: kag-2
        image: gpimblott/kag-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 50301
        env:
          - name: KAG_SV_NAME
            value: "King Arthur's Gold"
        resources:
          requests:
            memory: "2048Mi"
            cpu: "2"
---
kind: Service
apiVersion: v1
metadata:
  name: kag-2
  labels:
    app: kag-2
spec:
  selector:
    app: kag-2
  ports:
    - name: gameconnections
      protocol: UDP
      port: 50301
      targetPort: 50301
    - name: clientcommunication
      protocol: UDP
      port: 50382
      targetPort: 50382
    - name: autoupdates
      protocol: TCP
      port: 80
      targetPort: 80
    - name: api
      protocol: TCP
      port: 443
      targetPort: 443